Greeting.create(message: 'How are you?')
Greeting.create(message: 'Good Morning')
Greeting.create(message: 'Good afternoon')
Greeting.create(message: 'Hello Micronauts!')
Greeting.create(message: 'Great to have you here!')
